# Generated by Django 3.2.7 on 2022-05-29 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('type_document', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula De Extranjería'), ('PS', 'Pasaporte'), ('Nit', 'Nit')], max_length=20)),
                ('num_doc', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('direction', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('name_consultory', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='FactureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('quota', models.IntegerField(help_text='Cuotas en meses')),
                ('n_invoice', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('value_quote', models.IntegerField(blank=True, null=True)),
                ('total_payment', models.IntegerField(blank=True, null=True)),
                ('interest', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('doc_patient', models.CharField(blank=True, max_length=12, null=True)),
                ('fullname_patient', models.CharField(blank=True, max_length=150, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facture_client', to='factura.client')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facture_line',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='QuotaFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('num_quota', models.IntegerField()),
                ('value', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iva', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_facture', to='factura.factureline')),
            ],
            options={
                'verbose_name': 'Cuotas de Factura',
                'verbose_name_plural': 'Cuotas de Facturas',
                'db_table': 'quota_facture',
            },
        ),
        migrations.CreateModel(
            name='ProductsFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('num_products', models.IntegerField(default=1)),
                ('total_value', models.IntegerField(null=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factureline')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.product')),
            ],
            options={
                'verbose_name': 'Productos Factura',
                'verbose_name_plural': 'Productos Facturas',
                'db_table': 'products_facture',
            },
        ),
        migrations.CreateModel(
            name='PaymentsFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Fecha de Creacion')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Fecha de Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('type_payment', models.CharField(choices=[('TC', 'Tarjeta de Credito'), ('EF', 'Efectivo'), ('TR', 'Transferencia')], max_length=10)),
                ('total_payment', models.IntegerField()),
                ('n_consecutive', models.IntegerField(blank=True, null=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factureline')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
